# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-21 19:18
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('MedMOHApp', '0002_remove_specialusers_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='people',
            name='companyid',
            field=models.ForeignKey(default=9, on_delete=django.db.models.deletion.CASCADE, to='MedMOHApp.Company', verbose_name='\u0395\u03c4\u03b1\u03b9\u03c1\u03af\u03b1'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='country',
            name='abbr',
            field=models.CharField(max_length=10, unique=True, verbose_name='\u03a7\u03ce\u03c1\u03b1(2)'),
        ),
    ]
