# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-30 12:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MedMOHApp', '0004_examdocument'),
    ]

    operations = [
        migrations.AddField(
            model_name='examination',
            name='docfile',
            field=models.FileField(blank=True, null=True, upload_to='examdocuments/%Y/%m/%d'),
        ),
        migrations.AlterField(
            model_name='examination',
            name='daysoffgiven',
            field=models.IntegerField(blank=True, null=True, verbose_name='\u0397\u03bc\u03ad\u03c1\u03b5\u03c2 \u0386\u03b4\u03b5\u03b9\u03b1\u03c2'),
        ),
        migrations.AlterField(
            model_name='medicine',
            name='dateend',
            field=models.DateField(blank=True, null=True, verbose_name='\u0388\u03c9\u03c2'),
        ),
        migrations.AlterField(
            model_name='medicine',
            name='datestart',
            field=models.DateField(blank=True, null=True, verbose_name='\u0391\u03c0\u03cc'),
        ),
        migrations.AlterUniqueTogether(
            name='people',
            unique_together=set([('name', 'surname', 'companyid')]),
        ),
    ]
