# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-03 07:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MedMOHApp', '0007_auto_20170402_2105'),
    ]

    operations = [
        migrations.AlterField(
            model_name='examination',
            name='docfile',
            field=models.FileField(blank=True, null=True, upload_to='%Y/%m/%d'),
        ),
    ]
