# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-05 06:24
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MedMOHApp', '0009_people_amka'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='locations',
            name='countryid',
        ),
        migrations.RemoveField(
            model_name='locations',
            name='peoples',
        ),
        migrations.DeleteModel(
            name='Country',
        ),
        migrations.DeleteModel(
            name='Locations',
        ),
    ]
