# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-12 09:18
from __future__ import unicode_literals

from django.db import migrations, models
import gdstorage.storage


class Migration(migrations.Migration):

    dependencies = [
        ('MedMOHApp', '0010_auto_20170405_0924'),
    ]

    operations = [
        migrations.AlterField(
            model_name='examination',
            name='docfile',
            field=models.FileField(blank=True, null=True, storage=gdstorage.storage.GoogleDriveStorage(), upload_to='%Y/%m/%d'),
        ),
    ]
